// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension ApolloQueries.Objects {
  /// Autogenerated return type of RemoveReaction
  static let RemoveReactionPayload = Object(
    typename: "RemoveReactionPayload",
    implementedInterfaces: []
  )
}